### ISSUE TITLE
A few remarks on the current state of the app

### ISSUE THREAD

**Issue by y0LAs** [SteamAchievementNotifier/SteamAchievementNotifier#13]
Hello again!
I have a few remarks and suggestions I will put up here :

1. (Bug) For me, **changing the volume of the notification with the scroll wheel function doesn't work**, the volume is always at 100%. (I circumvent it by using Windows 10's _Volume Mixer_ but it resets to default volume when I close the app)
2. When unlocking a secret achievement, it doesn't show the hidden description. (We can say it without unlocking it by watching the global stats achievements)
3. (Suggestion) When changing the notification sound, it would be nice if the app would **remember the last used file location** instead of opening the Documents folder every time.
4. (Suggestion) I personally use "Windows Toast" achievement style because it is the only one that shows both the title of the achievement and the description, but it is really huge. I would like to be able to **remove the "Steam Achievement Notifier (v1.8)"** line (which is only visible on this specific style) that takes around 25% of the height.
5. (Bug?) When using the "Windows Toast" achievement style, and the "Show all achievement percentages" option is enabled, the percentage sign is not visible, unlike other styles. it just shows for example "Achievement name (32.5)"
6. (Suggestion) It would be nice to have the possibility to adjust the achievement notification opacity, just like the "Now tracking" notification.
7. (Remark) The notifications animation is affected by the Nvidia driver setting "Background application max framerate", so if people use it, they need to create a profile for Steam Achievement Notifier and disable it, or else the animation framerate will be jerky.
8. (Suggestion) an option to display the description of the achievement for every style. as currently the Xbox, PS4 and PS5 style do not display it, unlike the Steam notification.
9. (Suggestion) an option to revert settings to default values in case we mess up a bit.

That's it, sorry for the long post, I hope it highlighted some points that were missed before, and I hope everything will be doing fine, that the app will get the popularity it deserves and that it will be a good time investment on your part.

Again, I wish you a very nice day, and thank you for reading and responding to my posts in such a nice way. 😊
I hope this long post does not bother you in any way.

**Comment by SteamAchievementNotifier** [comment]
Hey again @y0LAs,

Thanks for the feedback - I'm always happy to hear suggestions and fix any bugs, so it's very much appreciated!

1. The volume scroll function will only work when the mouse is hovered over the "Preview Sound" icon box, so if the mouse is scrolled anywhere outside of this icon box, the volume will not change. If you are scrolling within the box and it is still not working, it may be worth resetting the app (via **Settings** > **Reset App to Default**) and testing the volume scroll function again _(Note: Resetting the app will remove your API Key/Steam64ID and will need to be re-entered via the Settings menu, so make sure to have a backup of these!)_
2. In the Steam Web API, Hidden achievement descriptions are blank (I'm assuming to prevent spoilers), so they cannot be easily obtained.
![image](https://user-images.githubusercontent.com/77490730/162575657-f27f159e-bbba-4da3-986b-1dc3421c35e5.png)
I have a somewhat working solution for this, but I'm planning to implement it in a future release.
3. This is also something that I will be looking into changing as I'll now be using another method for showing "Open File" dialogs via the app, which should support this functionality.
4. Each notification is based as closely as possible on it's equivalent design, so some achievement styles won't show certain information, and others will (this is the reason the Playstation notifications don't have descriptions, as mentioned in point 8). In the "original" styles (i.e. not based on any existing console/OS notification), all the information is included, but as replicating the console/OS notifications as closely as possible is the secondary goal of the app, adding additional granular control over every aspect of every achievement may be overwhelming to some users (not to mention a lot of work to implement!). That said, if you have an idea for a notification design that you would like to see in the app, you're welcome to contact me privately on Discord and I can work on porting your design into the app.
5. I'll look into this issue - I may have missed this in testing!
6. This is also something I can look into adding in a future release.
7. Thanks for letting me know - this will be useful when troubleshooting!
8. Covered in point 4 - although, Xbox notifications will show the description, but if the "Display Time" is set lower than a certain number, the description won't be shown (in order to allow for the notification to fit the selected display time). This method is used for multiple achievement styles, so if you don't see the description, increasing the value will allow it to be shown in the notification again.
9. As mentioned, the app can be reset to default via the Settings menu, but if you mean resetting all Customiser values to default, this might also be something I can look into.

Thanks again for the feedback, and it's no problem at all - glad to hear any suggestions!

**Comment by y0LAs** [comment]
Thank you very much! :)
Super glad you are taking every detail into account for future updates, that's awesome ^^

4. I would like to reformulate the point 4, as I find the notification really big because of the top line and its spacer dedicated to display "Steam Achievement Notifier (v1.8)".

7. And one other thing, the animation got jerky again, after looking at the .exe location in task manager, it seems to be because Steam Achievement Notifier clones itself in the temp folder in a randomly named folder, so it's useless to create a profile as the used .exe will change location every time. 
I don't know but maybe, using AppData instead would work?

Thank you again :)

**Comment by SteamAchievementNotifier** [comment]
Hey again @y0LAs,

More notifications will be added in the future, so I could look into making a simpler notification that would be more suitable.

In regards to the second point, a change was made in V1.82 to prevent multiple instances from being opened, but will be reverted in the next release, as it has caused issues for several users. I have another method that will be implemented instead, and will prevent the app from being extracted to random folders on each launch.

Thanks!

**Comment by y0LAs** [comment]
Cool, and thank you very much :)
