### ISSUE TITLE
Achievements in english

### ISSUE THREAD

**Issue by Com3Carne** [SteamAchievementNotifier/SteamAchievementNotifier#18]
First I would like to say Steam Achievement Notifier is amazing. I'm just having a problem (I think) like him. My language is Portuguese (Brazil), but the achievements (as the title says) come in English. Is there any way to change this?

**Comment by SteamAchievementNotifier** [comment]
Hey @Com3Carne - thanks for checking it out and I'm glad you like it!

Achievements should be translated for all languages where available - the only time they won't be translated into other languages is when the developers of the game you're playing haven't provided translations themselves. If you can let me know which game you're having this issue in, I'll double check whether it's an issue with the app or the game's achievement translations.

Thanks!

**Comment by Com3Carne** [comment]
It was Batman Arkham Knight. Other than that small problem, the program remains spectacular.

**Comment by SteamAchievementNotifier** [comment]
Hey again @Com3Carne - turns out I'm not actually able to check the translations for that particular game as I don't own it on Steam. If you're able to do the following, it would help me determine if there's an issue:

1. Copy this link: https://api.steampowered.com/ISteamUserStats/GetPlayerAchievements/v0001/?appid=208650&key=YOURAPIKEY&steamid=YOURSTEAM64ID&l=portuguese - this is the stats page for Batman Arkham Knight (***App ID: 208650***)
2. Paste it into the address bar in your browser, but before pressing enter, change "YOURAPIKEY"/"YOURSTEAM64ID" in the link to your API Key/Steam64 ID - this will load your achievement stats in the Steam Web API (along with achievement descriptions)
3. If the descriptions are written in English, it will be a game developer issue (i.e. they haven't translated the achievement descriptions for this game), otherwise, it's a SAN issue, which I can then look into!

 *⚠**Important**: If you're planning to send a screenshot of your findings, please make sure your API Key is not visible/is obscured somehow before posting!*

Thanks again!

**Comment by Com3Carne** [comment]
> Hey again @Com3Carne - turns out I'm not actually able to check the translations for that particular game as I don't own it on Steam. If you're able to do the following, it would help me determine if there's an issue:
> 
> 1. Copy this link: https://api.steampowered.com/ISteamUserStats/GetPlayerAchievements/v0001/?appid=208650&key=YOURAPIKEY&steamid=YOURSTEAM64ID&l=portuguese - this is the stats page for Batman Arkham Knight (_**App ID: 208650**_)
> 2. Paste it into the address bar in your browser, but before pressing enter, change "YOURAPIKEY"/"YOURSTEAM64ID" in the link to your API Key/Steam64 ID - this will load your achievement stats in the Steam Web API (along with achievement descriptions)
> 3. If the descriptions are written in English, it will be a game developer issue (i.e. they haven't translated the achievement descriptions for this game), otherwise, it's a SAN issue, which I can then look into!
> 
> _⚠**Important**: If you're planning to send a screenshot of your findings, please make sure your API Key is not visible/is obscured somehow before posting!_
> 
> Thanks again!

Hi, thank you very much for giving me some attention. Coming back to the point, it's actually in English. However, there is an error. At the end of the link, it is not in "Portuguese" but in "Brazilian". So the trophies are in Portuguese (Brazil).

Ex: https://api.steampowered.com/ISteamUserStats/GetPlayerAchievements/v0001/?appid=208650&key=YOURAPIKEY&steamid=YOURSTEAM64ID&l=**brazilian**

**Comment by SteamAchievementNotifier** [comment]
Hey again @Com3Carne,

Which language do you have set in the Settings menu in Steam Achievement Notifier? The "Brazilian-Portuguese" Steam-supported language hasn't been included in SAN - currently, only Portuguese (non-Brazilian) is able to be selected. So, if you have set the Language in SAN to Portuguese, the achievements will also show in Portuguese (non-Brazilian). This is the same with any other language selection in SAN - the language you have selected in the Settings menu will also translate the achievements. I can look into adding Brazilian-Portuguese as a supported SAN language if it would be preferable!

Also, just to confirm, the Batman Arkham Knight achievement descriptions were listed in English when viewing the Portuguese stats page?

Thanks!

**Comment by Com3Carne** [comment]
That's right, @SteamAchievementNotifier . Configured for Portuguese. I even thought that it was in fact the Brazilian, since the information on the screen looked a lot like what we speak here (Brazil) and not with Portuguese from Portugal. And no, the names/discretions of the achievements were all in English.

**Comment by SteamAchievementNotifier** [comment]
Hey again @Com3Carne,

Okay, thanks for testing/confirming! So, if the game supports achievement translations (which a lot do), the translated titles/descriptions will show in the notification when the achievement is unlocked (as long as your language in SAN is set to anything other than English). If your language is set in SAN but the achievement titles/descriptions are still showing in English, it will be because the game developers have not provided translations to the Steam Web API (which is where SAN gets this information from).

I will also look into adding Brazilian-Portuguese as a language option in future.

Thanks!

**Comment by Com3Carne** [comment]
Thank you very much, @SteamAchievementNotifier . Just because you consider adding Brazilian Portuguese is already a big deal. I look forward to future updates.

**Comment by SteamAchievementNotifier** [comment]
Hey @Com3Carne, I've released the latest App Revision which now adds the Portguese-Brazilian language!

If you have any translation suggestions, please let me know either here or on Discord.

Thanks!

**Comment by Com3Carne** [comment]
Hello, @SteamAchievementNotifier. Thanks for the great news. Where can I download this version?

**Comment by SteamAchievementNotifier** [comment]
Hey again @Com3Carne,

If you've downloaded [Version 1.84](https://github.com/steamachievementnotifier/steamachievementnotifier/releases/tag/1.84) (and unblocked **SANLauncher(V1.84).exe** as per the instructions in the Readme), it should be downloaded automatically after starting the app.

Thanks!

**Comment by Com3Carne** [comment]
Nice, @SteamAchievementNotifier . I hadn't noticed.
Thank you for everything.

**Comment by SteamAchievementNotifier** [comment]
No problem, thanks for checking it out!
