### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by AoiRingoz** [SteamAchievementNotifier/SteamAchievementNotifier#2]
I click the install.bat, and the powershell closes 1 second after, I unlocked the rar before extrac

**Comment by SteamAchievementNotifier** [comment]
Hello,

Apologies, it seems that a few people are having this issue. Are you an administrator on your system? Try right-clicking "_Install.bat_" and selecting "_Run as administrator_".

If that doesn't work, open the start menu, type "_Powershell_", right-click and select "_Run as administrator_". Once Powershell opens, copy/paste this line and press Enter:

`Start-Process C:\Users\$env:username\Downloads\SteamAchievementNotifier-systray\INSTALL.bat`

If the window still disappears, you may have to move the files manually:

1. Go into "Downloads" > "SteamAchievementNotifier-systray" > "temp" and copy all the files in this folder.
2. Click the File Explorer address bar and type (or copy/paste): `%localappdata%` and press Enter.
3. Create a new folder called `Steam Achievement Notifier`.
4. Paste all the files from the `C:\Users\%username%\Downloads\SteamAchievementNotifier-systray\temp` folder into the `C:\Users\%username%\AppData\Local\Steam Achievement Notifier` folder.
5. Right-click `SteamAchievementNotifier.ps1` and select "_Send To_" > "_Desktop_".
6. Go to your desktop and rename the new shortcut to `Steam Achievement Notifier`.
7. Right-click the shortcut and click "_Properties_". Click "_Change Icon..._", click "_Browse..._", go to `%localappdata%\SteamAchievementNotifier` and select "_steamcheev.ico_".

These are basically all the steps that "_INSTALL.bat_" does, but it automates it. Once done, just double-click the "_Steam Achievement Notifier_" desktop icon and it will run.

_Note: it should prompt you for your API Key/Steam64ID/Custom Sound after starting for the first time. If it doesn't for some reason, please let me know._

Hopefully this resolves your issue - please let me know if you need any more help.

Thanks!

**Comment by AoiRingoz** [comment]
I was able to install, but the notifier is not showing, and no sound are playing, I need to configure something with my notifications settings?

**Comment by SteamAchievementNotifier** [comment]
Do you have BurntToast installed? Open "Powershell" as admin and type `Find-Module burnttoast`. If you get an error saying it can't be found, you'll need to install the BurntToast module (this is what displays the achievement notifications):

1. In Powershell (running as admin), type: `Set-ExecutionPolicy bypass` (this allows downloaded .ps1 scripts and modules to be installed on your system. You can set this back after installing by typing: `Set-ExecutionPolicy Restricted`).
2. Type: `Install-Module BurntToast`

Thanks!

**Comment by AoiRingoz** [comment]
oh yes, I have it installed, just checked right now

**Comment by AoiRingoz** [comment]
I can't make it work

**Comment by SteamAchievementNotifier** [comment]
Hello,

I've been looking into this issue and the only way I can replicate it is moving the "_SteamAchievementNotifier-systray_" folder anywhere other than "_Downloads_". If the folder isn't extracted to and located in the root of your "_Downloads_" folder, the script can't run because it's hard-coded to move the files from `C:\Users\%username%\Downloads\steamachievementnotifier-systray\temp`. Once I moved the folder back into "_Downloads_", it ran without issue.

Please double check that your extracted "SteamAchievementNotifier-systray" folder is located there and try running "_INSTALL.bat_" again.

If this doesn't resolve the issue, did you download the .zip file from the [Releases](https://github.com/SteamAchievementNotifier/SteamAchievementNotifier/releases/tag/v1.2) page, or did you download via "_Code_" > "_Download ZIP_" on the main page? If you downloaded via the "_Code_" option, please try the Releases version instead.

Thanks!

**Comment by SteamAchievementNotifier** [comment]
Hi again,

If you still need help, [Version 1.4](https://github.com/SteamAchievementNotifier/SteamAchievementNotifier/releases/tag/1.4) has now been released - please give this version a try as it should be simpler to set up. Feel free to open a new issue if you're still having problems.

Thanks!
