### ISSUE TITLE
Sleep Mode Closes SAN

### ISSUE THREAD

**Issue by xyifer12** [SteamAchievementNotifier/SteamAchievementNotifier#30]
Hello again, I've returned with a puzzling issue once more. Today's issue is a very weird one; putting my PC to sleep silently closes SAN.

I first noticed this issue after playing a new Steam game and not getting any achievement popups at known unlock points. I initially thought that the particular game (MGS: Phantom Pain) was somehow incompatible with SAN and crashing it, but trying other Steam games proved this to not be the issue.

I have replaced my Windows 10 install with a completely new Windows 11 install since the last issue report I've submitted. I have also started using sleep mode on my PC since then, so unfortunately I am unable to determine whether this issue would be present on Windows 10.

I currently run SAN 1.84b.

The third party software I keep running in the background are as follows:
SuperF4
Steam
nVidia Broadcast
nVidia GeForce Experience (without passive recording enabled)
Razer Central
Eartrumpet

More system Information:
Windows 11 Pro 22H2 x64 English
ExplorerPatcher and OpenShell both installed and active.
nVidia DCH 526.86 Drivers installed.

**Comment by SteamAchievementNotifier** [comment]
Hey again @xyifer12,

SAN should quit/restart automatically when the PC is put to sleep - this is by design, as sleep mode seems to stop the app from functioning correctly for some reason. I implemented this solution a while ago and it seems to be working okay from my testing.

Has the **SANLauncher** EXE been moved since this issue started occurring? The launch path should be updated if the file is moved, but if it can't be located for whatever reason, the app will quit but be unable to relaunch from the last known path.

Could you check the `launchpath` key located in `%localappdata%\Steam Achievement Notifier (V1.8)\store\launcher.json` and see if it corresponds to your current **SANLauncher** file location?

Thanks!

**Comment by xyifer12** [comment]
SAN has not been moved, it remains in a subdirectory of my Documents folder. The path in launcher.json is correctly pointing to SAN Launcher's current location.

**Comment by SteamAchievementNotifier** [comment]
Hey again @xyifer12,

After looking through the code again, it seems that the actual **SteamAchievementNotifierV1.84.exe** file is being launched when restarting instead (as this prevents the splash screen/auto-updater from happening on relaunch). As long as that file is still present at `%localappdata%\Steam Achievement Notifier (V1.8)\store`, it should be able to launch without issue.

I'll see if I'm able to test using Windows 11, as I've had reports of other users having similar launching issues on that OS version. You could try the following to see whether it resolves this issue for you:

> - Open Windows Settings
> - Go to **Privacy & security** > **For developers** > **Terminal** > Set to **Windows Console Host**

This should ensure that commands are run via CMD instead of the new Windows Terminal app, which seems to cause issues for some reason.

Thanks!

**Comment by SteamAchievementNotifier** [comment]
Hey again @xyifer12,

Sorry to hear that hasn't resolved it. I'll see if I can get access to a Windows 11 device or VM to test with.

Thanks!

**Comment by xyifer12** [comment]
If there's any other information I can give that might be helpful, please let me know. Thank you for the continual support and the awesome software!

**Comment by xyifer12** [comment]
I'm very happy to report that today's update (11/Dec/2022) beta update has solved the issue for me! I have updated, put my computer to sleep, awakened it, and SAN is active in my system tray.

I'll wait 2 days to close the issue to give others time to comment on success or failure.
