### ISSUE TITLE
Wallpaper Engine Hogging the Game Detection

### ISSUE THREAD

**Issue by Krythulu** [SteamAchievementNotifier/SteamAchievementNotifier#34]
I was playing vampire survivors as a test for the app seeing how I don't have all the achievements and getting them isn't that hard. However I noticed in the main windows it was detecting notifications for Wallpaper Engine, not Vampire Survivors. My steam profile says I'm playing vampire survivors but the notifier just says wallpaper engine. Would suggest fixing this
![Screenshot 2022-12-27 150341](https://user-images.githubusercontent.com/94866697/209684800-49ea5f0f-e84d-40a3-a3b5-04bd2c9c54ec.png)

**Comment by SteamAchievementNotifier** [comment]
Hey @Krythulu - apologies for the late response on this!

The Steam Web API considers apps bought through the Steam store as games that are being "played", and if the developer of the app does not include workarounds to circumvent this behaviour, the Steam Web API will consider Wallpaper Engine to be the "game" that you are "playing", so it will be tracked instead of your desired game.

The usual workaround is to launch the app first (in this case, Wallpaper Engine), then launch the game - this will update your currently played game on the Steam Web API to the actual game. But as Wallpaper Engine is a persistent background app, it might exhibit different behaviour that prevents games from overriding it.

I don't own Wallpaper Engine so I can't test it, but for now, I would advise to either leave the app closed while using SAN, or contact the developer of Wallpaper Engine to see if there's a way to stop it from being registered as a game on the Steam Web API.

I'm currently working on a new major version of SAN that doesn't use the Steam Web API at all, so it might be worth checking whether you can replicate this issue once released.

Thanks!
