### ISSUE TITLE
Not saving screenshots 

### ISSUE THREAD

**Issue by Yecgaa01** [SteamAchievementNotifier/SteamAchievementNotifier#48]
Hi!
The option "screenshot with notification overlay" it's not working on 1.85.5 version.
Was working before on 1.84

**Comment by SteamAchievementNotifier** [comment]
Hey @Yecgaa01,

What exactly is not working when using the option? It seems to be okay in testing and for other users. Here's some things you can check:

- Have you changed the `Path` where your screenshots should be saved? If so, make sure the path is valid.
- Make sure you have selected the same monitor as your game in the `Monitor` dropdown list.
- Check the **App Log** (found in the **Settings** menu) to see if you are getting any errors when generating screenshots.

Thanks!

**Comment by Yecgaa01** [comment]
Morning! Thanks for your help

The screenshot of the achievement is no taken/saved

*Have you changed the Path where your screenshots should be saved? If so, make sure the path is valid.

A: yes, is the same folder i used in 1.84 version. I made a clean install and configured again. Nothing :(

Make sure you have selected the same monitor as your game in the Monitor dropdown list.

A:  II'm using only one monitor, and yes, he is selected.

Check the App Log (found in the Settings menu) to see if you are getting any errors when generating screenshots.

Ok, the last achievement log activity:

APPID: 814380
[8/27/2023, 6:36:28 AM][INFO]:
Re-checking unlock status for APPID: 814380
[8/27/2023, 6:36:29 AM][ERROR]:
"ss" could not be created: a window with label `ss` already exists
[8/27/2023, 6:36:29 AM][INFO]:
Re-checking unlock status for APPID: 814380
[8/27/2023, 6:36:29 AM][INFO]:
Final re-check of unlock status for APPID: 814380
[8/27/2023, 6:36:30 AM][INFO]:
Final re-check of unlock status for APPID: 814380
[8/27/2023, 7:33:36 AM][INFO]:
AppID is 0


what is "SS"?

My english is not very good, so i hope is undestandable

**Comment by SteamAchievementNotifier** [comment]
Hey again @Yecgaa01,

So, the `"ss" could not be created: a window with label "ss" already exists` means that there's already a screenshot window open when attempting to take a screenshot.

This will usually happen if you preview a screenshot via **Settings** > **Screenshot with Notification Overlay** > **Preview**, but don't close the window after previewing it - the **Preview** window that appears uses the same label as the actual screenshot (`ss`). I'll be looking to change this in a future update, but for now, make sure you haven't got any **Preview** windows open in the background when starting a game.

If you're sure you haven't got any other windows open other than the main app window, I would recommend uninstalling and reinstalling, making sure to enable the "Delete the application data" checkbox. After uninstalling, also delete the following folders:

- `C:/Users/%username%/AppData/Local/com.steamachievementnotifier.jackson0ne`
- `C:/Users/%username%/AppData/Local/SteamAchievementNotifier`
- `C:/Users/%username%/AppData/Roaming/com.steamachievementnotifier.jackson0ne`

This will fully uninstall the app, and allow it to be re-installed from scratch. I would also advise downloading the newest installer from the Releases page to rule out any weird issues caused by updating to V1.85.5 from an older version.

Let me know if you have any further issues with this.

Thanks!

**Comment by Yecgaa01** [comment]
It worked! Thank you!
