### ISSUE TITLE
[BUG] White screen when minimize on ROG ally

### ISSUE THREAD

**Issue by Nathan31973** [SteamAchievementNotifier/SteamAchievementNotifier#49]
When the application is running in the background minimize to the system tray a white get applied to the desktop unless you reopen the app or quit the app.
<img width="960" alt="image" src="https://github.com/SteamAchievementNotifier/SteamAchievementNotifier/assets/32977935/4d0fc382-9fc2-4086-8efe-bf2010065794">

**Comment by SteamAchievementNotifier** [comment]
Hey @Nathan31973,

SAN has been primarily tested on Windows PC versions, as I don't own any of the newer portable devices (such as SteamDeck or ROG Ally etc.), so generally, YMMV when running it on any other device.

If you're running the V1.85 Alpha version, I would imagine that the issue is related to the graphics driver's ability to handle transparency, as the SAN window is just made invisible and unclickable instead of being fully hidden (due to a focusing bug in the Tauri framework). So I would advise checking if there are any available driver updates for your system.

But outside of that, I'm not currently in a position where I can test on any devices other than PC, but if I come across any solutions, I'll let you know.

Thanks!

**Comment by Nathan31973** [comment]
Thanks for the response.

The Ally is entirely up-to-date with WIN11, OEM, and AMD drivers.

**Comment by SteamAchievementNotifier** [comment]
Hey @Nathan31973,

V1.9 has now been released, and has gone back to using Electron. Hopefully you shouldn't get the same behaviour on the new version, so let me know whether the issue is resolved after updating.

Thanks!

**Comment by Nathan31973** [comment]
V1.9 has fixed the issue. The UI scales great on the hand held screen
