### ISSUE TITLE
(Suggestion) Select current achievement/s being hunted

### ISSUE THREAD

**Issue by Tipzilla** [SteamAchievementNotifier/SteamAchievementNotifier#56]
Hey!

First off, this application is absolutely fantastic and is something I have been looking for for a very long time.

Secondly, I was wondering if it would be possible to allow the user to select a few achievements from the game they are playing that they are currently working towards unlocking.

This could be shown in a small GUI, that way you could easily remind yourself of the achievement and it's unlock requirements. But even more so, if this could be captured for streaming purposes, it would go a long way in enhancing the viewer experience and keep them up to date on all the info regarding the current achievement hunt. That way, once it's unlocked, it gets marked and you can select another one. It could maybe allow for displaying no more than 3? To keep things simple and clean.

Happy to expand on this and even provide a rough visual mock-up if requested!

**Comment by SteamAchievementNotifier** [comment]
Hey @Tipzilla,

Thanks very much for checking out the app 🙏 much appreciated, and I'm glad you're enjoying it!

I've experimented with adding this sort of overlay in a previous version, but since the Steam UI update, the Steam Overlay actually provides this information in the **Achievements** section, so I didn't work on a replacement for it.

It's possible to pin this menu over the game window, set the opacity and reorder achievements that you're currently tracking - and I believe it should update in realtime as well once the achievements are earned. It might be a better solution for you to use something that is already integrated into Steam itself as it's already a feature, and as I have a lot of ideas for improvements already, I can't guarantee that all feature requests will be implemented into SAN, let alone in any sort of timely manner 😅

If Steam's built-in solution isn't exactly what you're looking for, you're welcome to either post a mock-up here or join the server/PM me on Discord if you wanted to provide further info about it.

Thanks!

**Comment by Tipzilla** [comment]
Thanks for the reply!

I actually never thought about trying that now that Steam has updated their UI. I just messed around with it and pretty much got things how I wanted. Although, it is a shame Steam doesn't let you pin the overlay elsewhere because I'd certainly prefer to pin it on my second monitor, then have OBS capture that so I can move it anywhere in my OBS layout. So my compromise was to capture the game specific achievement window from the Steam client itself. Only downside is you can't organise achievements there so I have to rely on the search function.

But nevertheless it's roughly what I'm after.

Here's an example. (minus the black screen where my webcam would be)
![Screenshot 2024-05-25 16-42-01](https://github.com/SteamAchievementNotifier/SteamAchievementNotifier/assets/128940438/4ff1f8ae-1e37-4aa5-9827-c0a0752725f1)

Thank you again for the response and the great work on this app!

**Comment by SteamAchievementNotifier** [comment]
Hey again @Tipzilla,

Yeah, it's a limitation of the overlay that it can't be placed elsewhere, but the mock-up is useful in determining what it is you're after. It might be something I could look at further down the line, as it could incorporate extra functionality - such as animations when listed achievements are unlocked, integrated overview of overall user achievement stats (as shown by the showcase in your image), customisation of colours and layout etc.

I'll update here again if I manage to find some time to look into it - as it stands, I'll be mostly working on bug fixes, but I've also got a few additional customisation options that I want to look into as well, so they'll probably be worked on before I can look into dedicating some time to something like this.

Thanks!

**Comment by Tipzilla** [comment]
So, I had this idea earlier today and decided to test it out. 

![image](https://github.com/SteamAchievementNotifier/SteamAchievementNotifier/assets/128940438/97bec280-e4de-49bd-8675-c142dbe95c0b)

You can actually copy and paste achievements and their descriptions into a note if you grab them from the website. So you can customize a layout and whichever achievements you want to show. It not exactly a super nice look, but it works pretty well and can be captured directly through OBS as a window capture. You can also keep things organised easily as notes will be per game.

However, that's still not good enough for me so I decided to start making this idea into an actual app.

![image](https://github.com/SteamAchievementNotifier/SteamAchievementNotifier/assets/128940438/f607a2a9-5580-42d3-9ac0-e1b4a8a0b2f3)

This is the prototype so far, coded in C#.

**Comment by Tipzilla** [comment]
@SteamAchievementNotifier that's fantastic!

Pretty much exactly what I had in mind, it's perfect to provide a visual to Twitch viewers on the achievements that you're hunting etc.

Thanks for the great work!
