### ISSUE TITLE
Test notifications bindings working incorrectly with numbers

### ISSUE THREAD

**Issue by fantasygone** [SteamAchievementNotifier/SteamAchievementNotifier#59]
I already have CTRL + SHIFT + 1/2/3 in use so I was trying to use alternatives like CTRL + 1/2/3 + ENTER

But the thing is it keeps triggering the Main notification for all 3 cases even though I'm pressing different numbers. As I kept trying I also found out it triggers even only by pressing CTRL + ENTER, without numbers at all. Maybe this issue is something with the program ignoring number inputs? For now I've changed my binding to something else but it would be cool if this was fixed.

**Comment by SteamAchievementNotifier** [comment]
Hey @fantasygone,

I've just tested this - with `CTRL + 1 + Enter` (Main) and `CTRL + 2 + Enter` (Rare), I can replicate the issue. However, by entering the digit in the shortcut combination **last** - i.e. `CTRL + Enter + 1` and `CTRL + Enter + 2` - both notifications are triggered independently.

For shortcuts that do not use 2 accelerators (`CTRL`/`Shift`/`Alt` etc.), you may need to play around with the order of the key input to be able to use the preferred combination. As it does technically work, I wouldn't consider it to be a high priority fix, but I appreciate the report and will look into it to see if there is a resolution for a future release.

Thanks!

**Comment by fantasygone** [comment]
I understand; for the time being, I'll use the other shortcut I came up with.

I also have a question that I couldn't answer by searching the internet: Is there a way to disable the Steam achievement pop-up? For the first few times, SAN appears on the screen after a noticeable delay, as well as an audio delay in which the animation begins but is muted. In this regard, seeing the steam normal achievement before the notifier is somewhat defeating its purpose.

I've noticed a delay in test notifications as well.

**Comment by SteamAchievementNotifier** [comment]
Hey again @fantasygone,

Steam has built-in options to turn of toast notifications under Settings > Notifications > Show Notification Toasts... > Never. Bear in mind that this disables all Steam pop ups, including messages etc. But that's a Valve issue - not something I can do anything about!

If you're seeing delays in notifications appearing, it can be for a few reasons. The first notification being delayed could be due to having to cache the data/elements used in the notification - especially if you've set images/audio/fonts in the Customiser menu, and especially if those elements are also large in file size/resolution.

If you're seeing it more often, try enabling the **Settings** > **Disable Hardware Acceleration** option. This switches software (CPU) rendering rather than GPU, which may help if you either have lower-end hardware, or see delays or weird behaviour in games that take up a lot of GPU resources.

Thanks!

**Comment by fantasygone** [comment]
@SteamAchievementNotifier What is most noticeable is the sound delay, and yes I am using custom fonts/sounds/images.

The animation plays (XB Modern for all 3) and the sound can be heard a few seconds late.

**Comment by SteamAchievementNotifier** [comment]
Hey again @fantasygone,

I would advise trying the **Disable Hardware Acceleration** option and see if it improves things. Let me know whether this makes a difference for you.

Thanks!

**Comment by fantasygone** [comment]
It's still happening, and I want to mention my pc is not low-end.

AMD Radeon RX 6600M
AMD Ryzen 9 5900HX

**Comment by SteamAchievementNotifier** [comment]
Hey again @fantasygone,

Apologies for the late response - been busy with updates!

In terms of your delayed notifications issue, I'm not really sure what to suggest, outside of what I've already mentioned. I haven't had that issue reported very often, and when it has been, ticking the **Disable Hardware Acceleration** option has resolved it. For me, notifications appear instantaneously - even when loading custom asset files such as images/fonts etc. - so unfortunately, as I'm not able to replicate it, I believe it may be an issue with either your setup or something interfering with SAN on your system that may be causing that behaviour.

If you're able to provide any additional details or findings, please let me know and I can try and assist as much as I can.

Thanks!

**Comment by SteamAchievementNotifier** [comment]
Hey again @fantasygone,

I'm going to close this as it hasn't had a response in a while. If you manage to find any additional information regarding your specific issue, please feel free to let me know.

Thanks!
