### ISSUE TITLE
user folder with space issue

### ISSUE THREAD

**Issue by Saidinas** [SteamAchievementNotifier/SteamAchievementNotifier#6]
Hi there, I am not good at programming in general and English is not my native so I apologize if my explanation confuses you. the issue that I am having is that the app will open a Powershell window briefly then closes. There is no UI or anything. I tried to open the ps1 file with Powershell but I got this error:
C:\Users\USER : The term 'C:\Users\USER' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
I did some research regarding this matter and found out that my user folder has a space on its name, "USER DK" which may cause problems to the app since it is using Powershell that requires a "`" sign when writing path with a space on it. "C:\Users\USER` DK" for example. is there a way to fix this? renaming my user folder is possible but the steps are long and risky.
Thanks in advance!
Kind Regards.

**Comment by SteamAchievementNotifier** [comment]
Hey Saidinas,

Sorry to hear you're having issues. It seems that Powershell doesn't automatically account for spaces in usernames!

To troubleshoot this issue on your system, please do the following:
1. Open your Start menu, type "Windows Powershell" and open it.
2. Once loaded, type/paste: `$env:userprofile` and press Enter.
3. If Powershell says `$env:userprofile` is "**C:\Users\USER**", type/paste: `${env:userprofile}` and press Enter.

After step 3, Powershell _should_ say your _UserProfile_ path is "**C:\Users\USER DK**". If so, I'll make some changes and send you an edited script to try out.

Thanks!

**Comment by Saidinas** [comment]
hi there!
I really appreciate the respond.
I've followed your steps above, and yes indeed, it says my user profile path is "C:\Users\USER DK".
I have to apologize for the code that you have to modify since this is my pc's issue. for some reason the shop that I bought this laptop from, put a space on the user profile's name.

**Comment by SteamAchievementNotifier** [comment]
Hi again Saidinas,

Good to hear that your paths seem to be working with the above change. I've amended the script - if you're able to download [this file](https://github.com/SteamAchievementNotifier/SteamAchievementNotifier/files/7027646/SANGUI-V1.5.DEBUG.zip) and run "setup.exe", it should replace all your current files with the (hopefully) fixed version.

_Please note: As these are newly created .exe files, your antivirus software may block the file from being downloaded via a browser. If your browser/antivirus blocks the file from being downloaded, you can download it by opening a new Powershell window and typing/pasting `Invoke-WebRequest "https://github.com/SteamAchievementNotifier/SteamAchievementNotifier/files/7027646/SANGUI-V1.5.DEBUG.zip"-OutFile "${env:userprofile}\Downloads\SANGUI-V1.5(DEBUG).zip"`._

Please let me know whether this resolves your issue, as I will amend the current release and edit any future releases to include this change. And no apology necessary - it's good to find these issues so that others don't run into them later!

Thanks!

**Comment by Saidinas** [comment]
Hi there, after the installation process, a PowerShell window briefly opens and shows:
Processing -File 'C:\Users\USER' failed because the file does not have a '.ps1' extension. Specify a valid Windows Power Shell script file name, and then try again.

**Comment by SteamAchievementNotifier** [comment]
Hi again Saidinas,

Upon further testing, I think I've figured out the issue. Could you download [this file](https://github.com/SteamAchievementNotifier/SteamAchievementNotifier/files/7028117/REPLACESANGUI.zip) instead? (_It's another new .exe file, so you may have to download via Powershell: `Invoke-WebRequest "https://github.com/SteamAchievementNotifier/SteamAchievementNotifier/files/7028117/REPLACESANGUI.zip"-OutFile "${env:userprofile}\Downloads\REPLACESANGUI.zip"`_).

If you unzip the file and run "_sangui.bat_", it will automatically replace the existing "_SANGUI.exe_" in the `%localappdata%` folder. Once that's done, run Steam Achievement Notifier again and it should open this time!

Thanks!

**Comment by Saidinas** [comment]
hi there! 
indeed it works fine now! Thank you!
There is just one more odd issue though, but I am not sure if this is related to the profile issue or not.
After my first time successfully opening the app, I left it open in the background for a while, so I could set things up later because I had work to do. I notice during this time, the app took quite a bit of my CPU. A few minutes later, a PowerShell window briefly opened and closed repeatedly. sadly, I didn't have a chance to read it, since the display passed way too quickly. I had to restart my pc after that.
I decided to launch the app once more and set things up properly, adding my API key, id, and sound. everything looks fine now, aside from a bit of high CPU usage that I think is normal for the app. sound and notification works fine so far, which I tried by unlocking a few achievements. I have not encountered any PowerShell error yet.
I would like to say thank you once again for the fix and I appreciate your help! It feels so satessfying to unlock achievements now. you've made my day :)

**Comment by SteamAchievementNotifier** [comment]
Hey Saidinas,

Awesome, glad it's working for you now!

Unfortunately, the high CPU/RAM usage is due to using Winforms for the app, as well as running multiple background jobs for displaying notifications etc. I personally haven't found any noticeable performance loss while in-game while using it, but it's possible that this may affect users with less-capable hardware. I've made some adjustments to the way background jobs are discarded in Version 1.6 (which should be releasing very soon), so hopefully this mitigates some of the high resource usage.

I've also incorporated the username fix into the next version, so you shouldn't have any further issues.

I'm glad your other issue is now resolved after restarting your PC. As always, if you have any further issues with it, let me know. But it's no problem - I'm happy to help, and thanks a lot for trying out the app!
