### ISSUE TITLE
Duplicate instances in task manager

### ISSUE THREAD

**Issue by BrownInPlay** [SteamAchievementNotifier/SteamAchievementNotifier#62]
My game started stuttering real bad (normally fine), then after closing my PC was starting to be real sluggish, so I opened task manager and the Notifier had over 20 entries and was clogging nearly all my 32GB of RAM. I've only just updated to 1.9, and I've never had this issue before. 

I was playing an MMO with a launcher, so the pop-up of game tracking opened a couple of times, which was usually normal, but I just wonder if that had anything to do with all the multiple instances?

**Comment by SteamAchievementNotifier** [comment]
Hey @BrownInPlay,

Multiple instances of Steam Achievement Notifier processes appearing in Task Manager is usually normal, as Electron (the framework used for the app) is based on Chromium (also used in Edge/Chrome/Discord/Teams etc.). If you view running processes for any of the aforementioned apps, you'll see there are multiple entries - this is due to Chromium's separation of sub-processes, which allows the application to continue functioning if one area of it fails or crashes.

However, using that much memory and causing stuttering on the system is not normal, but I haven't personally seen that before, nor had any reports of it. However, if you're seeing multiple "**Now Tracking**" notifications, this usually [indicates a problem](https://github.com/SteamAchievementNotifier/SteamAchievementNotifier?tab=readme-ov-file#known-issues) which has been reported to be resolved by running SAN as administrator (as outlined in the link to the README). Alternatively, ticking **Settings** > **Advanced** > **Alt. Process Mode** has also seen some benefits by users experiencing multiple "**Now Tracking**" notification popups.

If this still does not resolve the issue for you, please attach all three available logs under **Settings** > **App Log** (you can change the selected log type using the dropdown at the top of the page), and I'll take a look at what's happening.

Thanks!

**Comment by BrownInPlay** [comment]
Thanks i'll try this out soon, as it happened again today but there were over 100 processes this time and my 3600 was pinned, couldn't open anything or even move the mouse and had to hard reset. This never happened in 1.8, but i'm loving all the new customisation - I'll let you know if the above fixes my problem :)

**Comment by SteamAchievementNotifier** [comment]
Hey again @BrownInPlay ,

Glad to hear that resolved it! Let me know if you have any further issues.

Thanks!
