### ISSUE TITLE
Game is not properly released after being closed

### ISSUE THREAD

**Issue by Arcane36** [SteamAchievementNotifier/SteamAchievementNotifier#64]
I am using the latest version of the Achievement Notifier. The game gets detected correctly when launching, however it almost never manages to close right. This leaves me with incorrect play times. Just yesterday I have played a game for 1 hour, but now Steam says I have played 16 hours because I have forgotten to check whether the game was released from the tool or not. 

I have tried sever versions, coming all the way down from 1.9.4 up to 1.9.7. I have tried to mess with the tracking and release delay and also to increase the max process retries, but to no avail. I still have to manually release every game.

The worst thing about it is, that if you buy a game, test it for an hour and maybe want to refund it for whatever reason, if you forget to check it, you might be out of luck because of a high play time.

If there is anything I can provide for you to help reproduce the bug, let me know. 
**My PC is**

- 13th Gen Intel(R) Core(TM) i5-13600KF   3.50 GHz
- 32 GB RAM
- RTX 4070Ti super
- Windows 11 PRO 23H2 22631.3810 (up to date)

**Comment by fantasygone** [comment]
![image](https://github.com/user-attachments/assets/3a463881-a610-47e5-98ae-88ca89d2351a)
I suggest doing this for the time being but that's an issue for me as well

**Comment by SteamAchievementNotifier** [comment]
Hey @Arcane36 ,

Due to the upgrade to Steamworks in V1.9, the way games are detected and subsequently released from SAN has had to change (*more info available in the README*).

Despite the many advantages of Steamworks vs the Steam Web API, a slight disadvantage is that running game processes have to now be manually located, due to Steamworks not providing a native function to check whether a game is running or not. If SAN can't find the current game process for whatever reason, it will need to be manually released.

I've basically done everything I can to ensure that most games are detected and released without issue, but as I'm sure you can appreciate, due to the massive amount of games available on Steam - plus their insistence to do all sorts of weird stuff before actually launching the game - it's essentially impossible to guarantee full compatibility with every game's individual launch process. So, some games - especially those with pre-game launchers - may experience issues when trying to track the executable file.

I would suggest two things:

1. If a particular game is having issues, I would suggest adding it as a **Linked Game** (*under **Settings** > **Linked Games***), which will check for a specific EXE every time SAN detects a specific AppID. This essentially takes the guesswork out of where to find the game's executable, so it should hopefully improve things.

2. If you're still having problems and Steam still says the game is being played after the game window has closed, you can manually release the game by right-clicking the system tray icon > **Options** > **Release Game**.

> The system tray icon also has an indicator to show whether SAN is still tracking a game or not:
>
> 🟢 Tracking
> 🔴 Not tracking

I appreciate that it's not ideal to have to manually release games once you're done, and I've tried as much as possible to ensure it doesn't happen, but currently, it's not feasible to account for every scenario, which is why these options are included in V1.9.

Thanks!

**Comment by fantasygone** [comment]
> 1. If a particular game is having issues, I would suggest adding it as a **Linked Game** (_under **Settings** > **Linked Games**_), which will check for a specific EXE every time SAN detects a specific AppID. This essentially takes the guesswork out of where to find the game's executable, so it should hopefully improve things.
> 
> Thanks!

I've linked Horizon Zero Dawn and now it closes properly, thanks!

**Comment by SteamAchievementNotifier** [comment]
Glad it helped, @fantasygone 👍

**Comment by Arcane36** [comment]
I see and I think I understand. The game in question is Star Wars Jedi Survivor and it opens up EA launcher upon running it. It's really unfortunate that there is no better way to track the games. I thought the 1.9 fixed it but oh well, nevermind. I understand and thank you for clarification :)
