### ISSUE TITLE
Achievement watcher integration

### ISSUE THREAD

**Issue by JesterForPirate** [SteamAchievementNotifier/SteamAchievementNotifier#70]
Any way at all to make this work with achievement watcher?

**Comment by SteamAchievementNotifier** [comment]
Hey @JesterForPirate,

This has been suggested before elsewhere, and from what I've been told, Achievement Watcher supports achievements for emulators whereas SAN is currently strictly Steam-based.

While it may be possible, the primary focus for SAN is - and always has been - for legitimate Steam games. While I'm not opposed to the idea of opening up the notification system for other platforms, it does take a lot of work to figure out how each one functions, and if one additional platform is integrated, others will continue to be requested. And once integrated, compatibility with platform changes/updates for each one would have to be maintained, which quite honestly, I personally don't have the time nor interest for. I don't personally use anything other than Steam for games, so that's where my primary focus is at.

If other devs want to look at the code and add integration into other platforms, I'm happy for PRs to be submitted. But currently, this is not planned, and has no in-built way to work with Achievement Watcher, as far as I am aware.

Thanks!
