### ISSUE TITLE
Persistent window or browser source to be captured by OBS

### ISSUE THREAD

**Issue by RuneMason1** [SteamAchievementNotifier/SteamAchievementNotifier#74]
### Has this feature previously been requested?

- [X] This feature has not been previously requested

### Feature Details

I don't use display captures for streaming, only game/window captures. I'd love this overlay to be capturable via OBS. It doesn't show up when I select "Capture 3rd party overlays" for the game source, I assume it's because it doesn't attach itself to the active game window in such a way that it's visible to OBS, but I could be wrong.

### Feature requests are considered, but not guaranteed

- [X] I understand that by requesting this feature for implementation within Steam Achievement Notifier, its inclusion will be considered, but not guaranteed

**Comment by SteamAchievementNotifier** [comment]
Hey @RuneMason1 ,

The notifications are spawned within a window and destroyed after the **Display Time** has been reached, mainly to save on resource, so it's not natively targetable by OBS etc.

However, under **Settings**, there's an option called **Stream Notifications**. If you enable it, an invisible, persistent window will be spawned that duplicates the contents of any on-screen notification, and as such, can be targeted as a source in OBS etc.

I think this is what you're looking for, so let me know if it resolves the issue.

Thanks!

**Comment by Alsonn** [comment]
Hi, I tried steam notifications and it works well but it's not saving this setting when I close the software. Is this normal ?

**Comment by SteamAchievementNotifier** [comment]
Hey again @RuneMason1,

It should re-open the window if you have **Stream Notifications** enabled when closing, but only if you actually click **Exit** via the system tray icon. If the app exits without explicitly selecting the **Exit** option, it will always revert the option on startup to prevent the window from being unnecessarily spawned.

Thanks!

**Comment by RuneMason1** [comment]
I'll check that in OBS next time I'm live, is it possible for the window to be hideable from the taskbar? Or... make it so it ONLY shows up when tracking?

**Comment by SteamAchievementNotifier** [comment]
Hey again @RuneMason1 ,

It's not possible to hide the window from the Taskbar, as this causes the window to become uncapturable due to an Electron quirk.

Test notifications are also sent to and displayed in this window, so I'm not planning on implementing the ability to only show it when tracking a game as this could cause issues and would take too much time to debug for a niche feature.

Thanks!

**Comment by RuneMason1** [comment]
Understandable. My next question would be if the achievements could be put in the game as a 3rd party overlay that obs would be able to see? Idk, just spitballing. :p I'm not even sure what the criteria are for that type of overlay.

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by SteamAchievementNotifier** [comment]
Hey again @RuneMason1 ,

There's a new option added in V1.9.16 called **Achievement Stats Overlay** (currently under **Settings** > **Media**) which is what I think you're asking for.

As this is no longer an issue, I'll close it for now.

Thanks!

**Comment by RuneMason1** [comment]
When I say overlay I mean things like steam's shift tab overlay. OBS can see and capture them as part of the game capture source.

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by SteamAchievementNotifier** [comment]
Hey again @RuneMason1 ,

I assume you mean overlaying notifications inside the game window itself? If so, the only way to do so would be to inject code into the game itself in order to display it within the window as a "true" overlay.

With so many games incorporating anti-cheat measures these days, this isn't something I am currently planning to pursue, as I don't want to risk the integrity of anyone's Steam account by using the app.

I've already added additional tools within the app to provide the functionality you're looking for, so in order to avoid risking negative consequences for users - plus the amount of work it would take to implement, along with the generally error-prone approaches to doing so - things will be staying as they are for now.

Thanks!
